### ISSUE TITLE
'sy process' tries to read from stdin and blocks forever

### ISSUE THREAD

**Issue by Byron-TW** [share-secrets-safely/cli#11]
If no TTY is attached, it will always try to read from stdin. However, this seems to block forever in certain situations, without indicating EOF or something similar.

Maybe there is a way to detect that, or to workaround it without forcefully providing something like `echo '{}' | sy process ...`.

**Comment by Byron** [comment]
Unfortunately so far I am unable to reproduce this issue. And if it could be reproduced, I wonder how it can be prevented automatically.
Something that could also work is some flag that explicitly tells `sy process` not to read from stdin.
