### ISSUE TITLE
Migrate single partition vault into multi partition one

### ISSUE THREAD

**Issue by lucaong** [share-secrets-safely/cli#21]
Hi there,
I am a very happy user of `sy`, and in my company we have setup a vault a long time ago. Now I would love to add partitions to it, but unfortunately I created it as a single-partition at the beginning, so if I try to add a partition named `devs` I get the following error:

```
error: Partition at './devs' is contained in another partitions resources directory at './.'
```

Is there a way, even manually, to migrate a single partition vault into a multi partition one?

I am using `sy` version `4.0.10`.

**Comment by Byron** [comment]
Hi Luca, long time no see!

regarding your question, I only know that sheesy relies entirely on human-readable configuration files, which makes it possible to manually migrate data.

Lacking clear memory on the folder/configuration structure, an active vault or the time to look into this right now, I recommend creating a multi-partition vault from scratch and see how it is configured. That way you should be able to migrate one to the format of the other.
If that doesn’t work for you, please let me know and I will take a look myself (tomorrow, it’s late here).

Cheers

**Comment by lucaong** [comment]
That sounds like a good idea. I will try and, in case, report here.

Hope you are doing great!

Cheers

**Comment by lucaong** [comment]
You were right, the process is quite simple, just a matter of manually creating folders for the partitions and adjusting the `sy-vault.yml` paths accordingly. For a single partition vault, migrating it into a multi partition setup basically means:

  - Creating a folder for the first partition
  - Moving all the files and folders apart from `sy-vault.yml` inside the newly created folder
  - Adjusting the paths in `sy-vault.yml` to reflect the new path (especially `secrets`, `gpg_keys` and `recipients`)
  - Creating other partitions with `sy vault partitions add`

I think the issue can be closed. Thanks a lot!
