### ISSUE TITLE
Fix new line when checking version

### ISSUE THREAD

**Issue by shakirshakiel** [share-secrets-safely/cli#5]
Hi,

I have been using this in my project. It is very useful for storing our passwords. Thanks.

However when I check the version it comes with a newline. 

```
shakir$./sy --version
sy 4.0.0

shakir$
```

Can you please fix this ?

**Comment by Byron-TW** [comment]
Happily! And great to hear you like the tool! Please let me know about everything you think could be improved, meeting my users requirements to me is the most important.
